### ISSUE TITLE
With Twist.linear.y wheels on both sides don't collaborate

### ISSUE THREAD

**Issue by 130s** [tork-a/spur#25]
I.e. wheels on right side rotate to the opposite direction from what wheels on left side rotate to.
Using #22.

**Comment by 130s** [comment]
```$ rostopic pub /spur/cmd_v geometry_msgs/Twist "linear: {x: 0, y: 0.01}"``` makes all 4 wheels turn toward the center of the robot.

```$ rostopic pub /spur/cmd_v geometry_msgs/Twist "linear: {x: 0, y: -0.01}"``` makes the opposite; all 4 wheels turn outward from robot's center.

**Comment by 130s** [comment]
The same issue happens with `roslaunch spur_gazebo spur_world.launch`.

**Comment by 534o** [comment]
check if this resolved by removing #22

--
◉ Kei Okada

**Comment by 130s** [comment]
Fixed via https://github.com/tork-a/spur/pull/31
